# This is a basic workflow to help you get started with Actions

name: Wiki Watcher

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  gollum:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: benmatselby/gollum-page-watcher-action@v1.4.0
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_CHANNEL: #custom-event-github-wiki-updates
        SLACK_USERNAME: Gollum
